a   :  n  : "file 1"
b   :  nv : "tela inteira para cima"
c   :  vi : "normal mode"  
d   :  nv : "page down"
e   :  n  : "abrir harpoon"
f   :  nv : "tela inteira para baixo"
g   :  n  : "git files"
h   :  i  : "signature help"
i   :  n  : "histórico pos ->"
I   :  n  : "próxima aba"
n   :  i  : "autocomplete ->"
o   :  n  : "histórico pos <-"
o   :  i  : "executa um comando e volta para o insert mode"
p   :  i  : "autocomplete <-"
p   :  o  : "preview"
q   :  n  : "selecionar todo o arquivo"
r   :  n  : "redo"
s   :  n  : "file 2"
t   :  o  : "abrir em nova aba"
u   :  nv : "page up"
u   :  i  : "apaga até o início da linha"
v   :  n  : "visual block mode"
w   :  i  : "apaga a palavra antes do cursor"
x   :  n  : "file 4"
z   :  n  : "file 3"

space :  i  : "auto-complete"
\     :  n  : "terminal"
]     :  n  : "vai para a definição"
