a   :  n  : "adicionar ao harpoon"
b   :  n  : "ir para inicio da linha preenchida"
c   :  n  : "coloca uma vírgula no fim da linha e salva o arquivo"
d   :  nv : "deleta sem copiar"
e   :  n  : "abre janela do erro"
ff  :  n  : "find files"
fw  :  n  : "find word"
gs  :  n  : "git status"
h   :  nv : "flash"
k   :  n  : ":Act "
l   :  n  : "lazy"
m   :  n  : "reload file"
nh  :  n  : "janela a esquerda"
nj  :  n  : "janela abaixo"
nk  :  n  : "janela acima"
nl  :  n  : "janela a direita"
nn  :  n  : "próxima janela"
p   :  n  : "colar varias vezes o mesmo conteudo"
qd  :  n  : "não salva abas ao fechar"
ql  :  n  : "abre ultimas abas a serem fechadas"
qq  :  n  : "fecha tudo"
qs  :  n  : "reabre abas que foram abertas neste caminho"
qS  :  n  : "menu para escolher histórico de abas abertas"
r   :  n  : "roda o arquivo"
s   :  n  : "substitui a palavra selecionada pelo valor desejado"
ss  :  n  : "oil"
tn  :  n  : "nova aba"
# tt  :  n  : "abrir terminal"
u   :  n  : "undotree"
w   :  n  : "salva o arquivo"
x   :  n  : "chmod +x"
y   :  nv : "copia para o clipboard"
yp  :  o  : "copia o caminho"

1   :  n  : "aba nº1" 
2   :  n  : "aba nº2" 
3   :  n  : "aba nº3" 
4   :  n  : "aba nº4" 
5   :  n  : "aba nº5" 
6   :  n  : "aba nº6" 
7   :  n  : "diminui largura da janela"
8   :  n  : "aumenta largura da janela"
9   :  n  : "diminui altura da janela"
0   :  n  : "aumenta altura da janela"
