a   :  n  : "insert mode no caractere seguinte"
A   :  n  : "insert mode no fim da linha"
b   :  nv : "palavra para trás"
c   :  v  : "apaga e insert mode"
C   :  n  : "apaga caracter atual até o fim da linha e insert mode"
C   :  v  : "apaga e insert mode"
d   :  v  : "deleta seleção"
D   :  n  : "deleta o caracter atual até o fim da linha"
dd  :  n  : "deleta linha"
e   :  nv : "final da palavra"
f   :  nv : "vai até o caracter selecionado (frente)"
F   :  nv : "vai até o caracter selecionado (atras)"
G   :  nv : "fim do arquivo"
gc  :  v  : "comenta texto selecionado"
gcc :  n  : "comenta linha"
gg  :  nv : "inicio do arquivo"
gs  :  o  : "ordenar"
gx  :  o  : "abre no navegador de arquivos"
g.  :  o  : "mostra arquivos escondidos"
h   :  nv : "esquerda"
H   :  nv : "topo da tela visivel"
i   :  n  : "insert mode"
I   :  n  : "insert mode no início da linha"
j   :  nv : "baixo"
J   :  n  : "move linha debaixo para o fim da linha atual"
J   :  v  : "move texto selecionado para baixo"
k   :  nv : "cima"
K   :  n  : "info"
K   :  v  : "move texto selecionado para cima"
l   :  nv : "direita"
L   :  nv : "final da tela visivel"
M   :  nv : "meio da tela visivel"
n   :  n  : "próxima opção"
N   :  n  : "opção anterior"
o   :  n  : "cria nova linha abaixo e insert mode"
O   :  n  : "cria nova linha acima e insert mode"
p   :  n  : "paste"
Q   :  n  : "desativado"
qq  :  n  : "fecha janela"
r   :  n  : "mudar caracter"
S   :  n  : "apaga linha atual e entra no insert mode"
sa  :  v  : "escolher surrounder"
sd  :  n  : "remover surrounder"
sf  :  n  : "achar surrounding"
sF  :  n  : "achar surrounding"
sr  :  n  : "substituir surrounder"
t   :  nv : "move para antes do caracter selecionado (frente)"
T   :  nv : "move para antes do caracter selecionado (atras)"
u   :  n  : "undo"
v   :  n  : "visual mode"
v   :  v  : "normal mode"
V   :  n  : "visual line mode"
V   :  v  : "normal mode"
w   :  nv : "palavra para frente"
x   :  n  : "remove caracter atual"
x   :  v  : "apaga"
X   :  n  : "remove caracter anterior"
X   :  v  : "apaga"

<CR> :  o  : "Entrar no diretório/arquivo"
-    :  o  : "Subir um diretório"
