#!/bin/bash


source "./act_comp" 2>/dev/null || source "$HOME/repos/dotfiles/scripts/act_comp"
# SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
# source "$SCRIPT_DIR/act_comp"

MINICONDA_PATH="$HOME/miniconda3"
UV_PATH=(/usr/lib/python*/site-packages/uv)
UV_CONDA_PATH=("$HOME"/miniconda3/lib/python*/site-packages/uv)

deactivate_env() {
    if [ -d "$MINICONDA_PATH" ]; then
        conda activate base
        if [[ -d "${UV_CONDA_PATH}" ]]; then
            deactivate 2>/dev/null
        fi
    fi
    if [[ -d "${UV_PATH[0]}" ]]; then
        deactivate 2>/dev/null
    fi
}

menu_f() {
    local repo_config="$1"
    local -n view="$2"
    local run="$3"
    local -n arr="$4"

    while true; do
        "${view[@]}" "$repo_config" >&2
        local choice; read -r -p "Escolha uma opção ou q para sair: " choice
        [[ "$choice" == "q" ]] && return 1

        if [[ ! $choice =~ ^-?[0-9]+$ ]]; then
            echo "Valor fornecido nao e um numero." >&2
            continue
        fi

        if (("${choice}" > "${#arr[@]}" || "${choice}" < 1)); then
            echo "Escolha invalida." >&2
            continue
        fi
        printf "%d\n" "$((choice - 1))" && return 0
    done
}

env_handling() {
    local repo_config="$1"
    local path="$2"
    local lang="$repo_config"

    case "$lang" in
        uv-python)
            source "${path}/.venv/bin/activate"
            ;;
        none) deactivate_env ;;
    esac
}

env_menu() {
    local bcat=()

    if bat --version 2>/dev/null >&2; then
        bcat+=("bat")
    else
        bcat+=("cat" "-n")
    fi

    local repo="$1"
    local menu="$2"
    local path="$3"
    local index=$((0))
    local repo_config=".act/env"

    [[ ! -f "$repo_config" ]] && echo "Configuração de ${repo} não encontrada." >&2 && return 1

    local lines; mapfile -t lines < "$repo_config"
    if [[ "$menu" == true ]]; then
        if [[ "${#lines[@]}" == 1 ]]; then
            echo "Só uma opção de ambiente disponível..."
            env_handling "${lines[$index]}" "$path" 
            return 0
        fi
        index=$(($(menu_f "$repo_config" bcat "$run" lines))) || return 1
    fi
    env_handling "${lines[$index]}" "$path" 
    return 0
}

language_handling() {
    local repo_config="$1"
    local run="$2"
    local path="$3"
    local vim="$4"

    local lang=""
    local from_path=""
    local exec_type=""
    local exec_path=""

    if [[ -n "$repo_config" ]]; then
        lang="${repo_config%%:*}"
        from_path="${repo_config##*:}"
        repo_config="${repo_config#*:}"
        repo_config="${repo_config%:*}"
        exec_type="${repo_config%%:*}"
        exec_path="${repo_config##*:}"
        if [[ "$vim" == true ]]; then
            nvim "$from_path"
            return 0
        else
            cd "$from_path" || return
        fi
    fi

    [[ "$vim" == true ]] && nvim "$path" && return 0
    [[ "$run" == "false" ]] && return 0

    case "$lang" in
        python) 
            python_exe=""
            for py_exe in python3 python; do
                if $py_exe --version >/dev/null 2>&1; then
                    python_exe=$py_exe
                fi
            done
            if [[ -z "$python_exe" ]]; then
                echo "Python não encontrado no sistema..." >&2
                return 1
            fi
            if [[ "$run" == true ]]; then
                $python_exe "$exec_path"
            fi
            ;;
        uv-python)
            if [[ "$run" == true  ]]; then
                uv run "$exec_path"
            fi
            ;;
        odin)
            if [[ "$run" == true ]]; then
                if [[ "$exec_type" == "d" ]]; then
                    odin run "$exec_path"
                else
                    odin run -file "$exec_path"
                fi
            fi
            ;;
        none)
            [[ "$run" == true ]] && echo "Linguagem de execução não especificada." >&2 && return 1
            ;;
        *)
            echo "Linguagem \"${lang}\" ainda não teve sua execução mapeada." >&2
            return 1
            ;;
    esac
}

starting_point_menu() {
    local bcat=()

    if bat --version 2>/dev/null >&2; then
        bcat+=("bat")
    else
        bcat+=("cat" "-n")
    fi

    local repo="$1"
    local menu="$2"
    local run="$3"
    local path="$4"
    local vim="$5"
    local index=$((0))
    local repo_config=".act/starting_point"

    [[ ! -f "$repo_config" ]] && echo "Configuração de ${repo} não encontrada." >&2 && return 1

    local lines; mapfile -t lines < "$repo_config"
    [[ ((${#lines[@]} == 0)) && "$run" == true ]] && echo "Nenhum ponto de partida cadastrado para este projeto." >&2 && return 1
    if [[ "$menu" == true ]]; then
        ((${#lines[@]} == 0)) && echo "Nenhum ponto de partida cadastrado..." >&2 && return 0
        if [[ "${#lines[@]}" == 1 ]]; then
            echo "Apenas uma opção de ponto de início disponivel..."
            language_handling "${lines[$index]}" "$run" "$path" "$vim"
            return 0
        fi
        index=$(($(menu_f "$repo_config" bcat "$run" lines))) || return 1
    fi
    language_handling "${lines[$index]}" "$run" "$path" "$vim"
    return 0
}

act() {
    local OPTIND

    local iniciar=false
    local vim=false
    local git_status=false
    local specific_starting_point=false
    local specific_env=false
    local project_path=false

    local erro=""

    local opt; while getopts ":xvghepr" opt; do
        case $opt in
            x) iniciar=true ;;
            p) specific_starting_point=true ;;
            e) specific_env=true ;;
            v) vim=true ;;
            g) git_status=true ;;
            r) project_path=true ;;
            h)
                msg=()
                msg+=("act -v repo")
                msg+=("act -g repo")
                msg+=("act -x repo")
                msg+=("act -ex repo")
                msg+=("act -e repo")
                msg+=("act -p repo")
                msg+=("Flags:")
                msg+=("v - Abrir com neovim.")
                msg+=("g - Git Fetch e Status no repo.")
                msg+=("x - Inicia o projeto a partir da primeira config presente no arquivo act.")
                msg+=("p - Menu para escolher como rodar o projeto.")
                msg+=("e - Menu para escolher ambiente.")
                msg+=("r - Apenas vai para o diretório do projeto.")
                printf "\n%s\n%s\n%s\n%s\n%s\n%s\n\n%s\n\n%s\n%s\n%s\n%s\n%s\n%s\n\n" "${msg[@]}"
                return 1
                ;;
            \?) erro+=$(printf "Flag -%s é inválida. " "$OPTARG") ;;
        esac
    done

    if [[ -n "$erro" ]]; then
        echo "$erro" >&2
        return 1
    fi

    shift $((OPTIND - 1))

    local repo="$1"
    local file="$HOME/.act_projects"
    if [[ ! -f "$file" ]]; then
        echo "Primeiro adicione um projeto." >&2
        return 1
    fi

    if [ -z "$repo" ]; then
        cd "$HOME" || return
        deactivate_env
        return 1
    fi

    local found_repo=false
    local curr_repo=""

    local path; while read -r path; do
        curr_repo="$path"
        if [[ "${path##*/}" == "$repo" ]]; then
            found_repo=true
            break
        fi
    done < "$file"

    if [[ "$found_repo" == true ]]; then
        cd "$curr_repo" || return

        [[ "$project_path" == true ]] && return 0

        if [[ "$git_status" == true ]]; then
            echo
            git fetch
            git branch -a
            echo
            git status
            echo
        fi

        env_menu "$repo" "$specific_env" "$curr_repo"
        starting_point_menu "$repo" "$specific_starting_point" "$iniciar" "$curr_repo" "$vim"
    else
        echo "Repo não existe." >&2
        return 1
    fi
}

_act_completion() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    [[ "$prev" == "act" || "$prev" =~ -[xpevgr]+ ]] && mapfile -t COMPREPLY < <(compgen -W "$(_get_projects)" -- "$cur")
}
complete -F _act_completion act
