#!/bin/bash


# _get_conda_envs() {
#     local envs=()
#     while read -r name _; do
#         [[ $name == "#" || -z $name ]] && continue
#         envs+=("$name")
#     done < <(conda info --envs)
#     printf '%s\n' "${envs[@]}"
# }

_get_linguagens() {
    printf '%s\n' various python lua bash c-sharp go odin markdown uv-python
}

_get_projects() {
    local files_path="$HOME/.act/projects"
    [[ -d "$files_path" ]] || return 1 

    for repo in "$files_path"/*; do
        echo "${repo##*/}"
    done
}
