#!/bin/bash


source "./act_comp" 2>/dev/null || source "$HOME/repos/dotfiles/scripts/act_comp"

actls() {
    local file="$HOME/.act_projects"
    local repo=""
    local current_dir=false
    local cwd="$(pwd)"

    local OPTIND
    local erro=""

    local bcat=()

    if bat --version 2>/dev/null >&2; then
        bcat+=("bat")
    else
        bcat+=("cat" "-n")
    fi

    while getopts ":r:hc" opt; do
        case $opt in
            r) repo="$OPTARG" ;;
            c) current_dir=true ;;
            h)
                msg=()
                msg+=("actls")
                msg+=("actls -c")
                msg+=("actls -r nome-repo")
                msg+=("Flags:")
                msg+=("r - Nome do repositório.")
                msg+=("c - Projeto do diretorio atual.")
                printf "\n%s\n%s\n%s\n\n%s\n\n%s\n%s\n\n" "${msg[@]}"
                return 1
                ;;
            :) erro+="Flag -$OPTARG necessita de um argumento. " ;;
            \?) erro+="Flag -$OPTARG desconhecida. " ;;
        esac
    done

    [[ -n "$erro" ]] && echo "$erro" >&2 && return 1
    [[ ! -f "$file" ]] && echo "Adicione um projeto com actadd primeiro." >&2 && return 1
    [[ "$current_dir" == true ]] && repo="${cwd##*/}"

    if [[ -n "$repo" ]]; then
        if ! act "$repo"; then
            local found=false
            local next_dir=true
            local prev_dir=""
            local curr_dir=""
            local answer=""
            while ! "$found"; do
                if [[ "$next_dir" == true ]]; then
                    prev_dir="$(pwd)"
                    cd ..
                    curr_dir="$(pwd)"
                fi
                [[ "$prev_dir" == "$curr_dir" ]] && echo "Projeto não encontrado." >&2 && cd "$cwd" && return 1
                [[ ! -d "${curr_dir}/.act" ]] && continue
                repo="${curr_dir##*/}"
                read -r -p "Selecionar projeto \"${repo}\" [Y/n] or q to quit " answer
                [[ -z "$answer" ]] && answer="y"
                answer="${answer,,}"
                case "$answer" in
                    y) found=true ;;
                    n) next_dir=true ;;
                    q) cd "$cwd" && return ;;
                    *) echo "Valor desconhecido." && next_dir=false ;;
                esac
            done
        fi
        "${bcat[@]}" ".act"/*
        cd "$cwd"
    else
        "${bcat[@]}" "$file"
    fi
}

_actls_completion() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    case "$prev" in
        -r)
            mapfile -t COMPREPLY < <(compgen -W "$(_get_projects)" -- "$cur")
            ;;
    esac
}
complete -F _actls_completion actls
