#!/bin/bash


actrm() {
    local act_path="$HOME/.act_projects"
    local project_dir=".act"
    local cwd="$(pwd)"
    local repo="${cwd##*/}"

    local OPTIND
    local erro=""

    while getopts ":h" opt; do
        case $opt in
            h)
                msg=()
                msg+=("actrm")
                printf "\n%s\n\n" "${msg[@]}"
                return 1
                ;;
            :) erro+="Flag -$OPTARG necessita de um argumento. " ;;
            \?) erro+="Flag -$OPTARG desconhecida. " ;;
        esac
    done

    [[ -n "$erro" ]] && echo "$erro" >&2 && return 1
    local temp=$(mktemp)

    if [[ ! -d "$project_dir" ]]; then
        echo "Projeto $repo não encontrado." >&2
        return 1
    else
        rm -rf "$project_dir"
    fi

    while read -r path; do
        [[ "${path%%:*}" == "$cwd" ]] && continue
        echo "$path" >> "$temp"
    done < "$act_path"

    mv "$temp" "$act_path"
}
