#!/bin/bash


source "./act_utils" 2>/dev/null || source "$HOME/repos/dotfiles/scripts/act_utils"

actrm() {
    local act_path="$HOME/.act_projects"
    local project_dir=".act"
    local cwd="$(pwd)"
    local repo="${cwd##*/}"

    local OPTIND
    local erro=""

    local opt; while getopts ":h" opt; do
        case $opt in
            h)
                msg=()
                msg+=("actrm")
                printf "\n%s\n\n" "${msg[@]}"
                return 1
                ;;
            :) erro+="Flag -$OPTARG necessita de um argumento. " ;;
            \?) erro+="Flag -$OPTARG desconhecida. " ;;
        esac
    done

    [[ -n "$erro" ]] && echo "$erro" >&2 && return 1
    local temp=$(mktemp)

    if [[ ! -d "$project_dir" ]]; then
        repo=$(_act_recursive_search "$repo" "$cwd") || return 1
        act "$repo"
        rm -rf "$project_dir"
        cd "$cwd"
    else
        rm -rf "$project_dir"
    fi

    local path
    while read -r path; do
        [[ "${path##*/}" == "$repo" ]] && continue
        echo "$path" >> "$temp"
    done < "$act_path"

    mv "$temp" "$act_path"
}
